# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'microsoft'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Maven Clean
      run: mvn clean --file pom.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml
   
    - name: List files
      run: ls target/
      
    - name: print tag name
      run: echo ${GITHUB_REF##*/v}
      
    - name: Test jar file
      run: java -jar target/sem-${GITHUB_REF##*/v}-jar-with-dependencies.jar
      
    - name: Rename jar file
      id: rename
      run: |
        cp target/sem-${GITHUB_REF##*/v}-jar-with-dependencies.jar target/sem-${GITHUB_REF##*/}.jar
        echo "new_name=target/sem-${GITHUB_REF##*/}.jar" >> $GITHUB_OUTPUT
      
    - name: Pack jar file
      run: |
        tar -zcvf target/sem-${GITHUB_REF##*/v}.tar.gz ${{ steps.rename.outputs.new_name }}
        rm ${{ steps.rename.outputs.new_name }}
      
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/*.jar,target/*.tar.gz"
          
          
